### ISSUE TITLE
Create the python package

### ISSUE THREAD

**Issue by heitor57** [irec-org/irec#3]
#### Tasks
- [x] Organize the folder structure
- [x] Create the local package
- [x] Check requirements
- [x] Deploy the package to pypi
- [x] Include in README the pypi package and instructions to use
